AWSTemplateFormatVersion: '2010-09-09'
Description: 'Drone C2 Operator Dashboard - Node-RED UI (Fixed - references command pipeline stack)'

Parameters:
  CommandPipelineStackName:
    Type: String
    Default: 'drone-c2-command-pipeline'
    Description: 'Name of the command pipeline stack (contains API Gateway, Cognito, etc.)'
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'VPC ID where dashboard will be deployed'
  
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: 'Public subnet ID for dashboard instance'
  
  AllowedCIDR:
    Type: String
    Default: '0.0.0.0/0'
    Description: 'CIDR allowed to access dashboard'
  
  KeyPairName:
    Type: String
    Default: ''
    Description: 'EC2 Key Pair (optional)'

Conditions:
  HasKeyPair: !Not [!Equals [!Ref KeyPairName, '']]

Resources:
  DashboardSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: drone-c2-dashboard-sg
      GroupDescription: 'Node-RED dashboard security group'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1880
          ToPort: 1880
          CidrIp: !Ref AllowedCIDR
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCIDR
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  DashboardRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: drone-c2-dashboard-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: ReadCommandPipelineStack
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: cloudformation:DescribeStacks
                Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${CommandPipelineStackName}/*'
              - Effect: Allow
                Action: ec2:DescribeTags
                Resource: '*'

  DashboardProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref DashboardRole

  DashboardInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      InstanceType: t3.small
      IamInstanceProfile: !Ref DashboardProfile
      SecurityGroupIds:
        - !Ref DashboardSecurityGroup
      SubnetId: !Ref SubnetId
      KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref 'AWS::NoValue']
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log) 2>&1
          set -e
          
          echo "=== Node-RED Setup Started: $(date) ==="
          
          # Install Node.js 20
          curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
          dnf install -y nodejs git curl jq
          
          # Install Node-RED
          npm install -g --unsafe-perm node-red
          mkdir -p /root/.node-red && cd /root/.node-red && npm init -y
          npm install node-red-dashboard node-red-node-ui-table aws-sdk
          
          # Settings
          cat > /root/.node-red/settings.js << 'EOF'
          module.exports = {
              uiPort: 1880, uiHost: "0.0.0.0",
              httpAdminRoot: '/admin', httpNodeRoot: '/',
              userDir: '/root/.node-red/', flowFile: 'flows.json',
              functionGlobalContext: { AWS: require('aws-sdk') }
          }
          EOF
          
          # Systemd service
          cat > /etc/systemd/system/node-red.service << 'EOF'
          [Unit]
          Description=Node-RED
          After=network.target
          [Service]
          ExecStart=/usr/bin/node-red --settings /root/.node-red/settings.js
          Restart=always
          User=root
          [Install]
          WantedBy=multi-user.target
          EOF
          systemctl daemon-reload && systemctl enable node-red
          
          # Fetch config from command pipeline stack
          REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
          API_URL=$(aws cloudformation describe-stacks --stack-name "${CommandPipelineStackName}" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text)
          USER_POOL=$(aws cloudformation describe-stacks --stack-name "${CommandPipelineStackName}" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text)
          CLIENT_ID=$(aws cloudformation describe-stacks --stack-name "${CommandPipelineStackName}" --region "$REGION" --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text)
          
          cat > /root/.node-red/aws-config.json << EOF
          {"apiUrl":"$API_URL","cognitoUserPoolId":"$USER_POOL","cognitoClientId":"$CLIENT_ID","region":"$REGION"}
          EOF
          
          # Download flows
          curl -f -o /root/.node-red/flows.json "https://raw.githubusercontent.com/AryaMajumder/cloud-to-drone-command-pipeline/main/drone%20command%20link/node-red-command-button.conf" || echo '[]' > /root/.node-red/flows.json
          
          systemctl start node-red
          sleep 5
          
          if systemctl is-active --quiet node-red; then
            IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
            echo "=== SUCCESS! Dashboard: http://$IP:1880/ui ==="
          else
            echo "=== FAILED ===" && journalctl -u node-red -n 50 --no-pager
          fi
      Tags:
        - Key: Name
          Value: drone-c2-dashboard

Outputs:
  DashboardURL:
    Value: !Sub 'http://${DashboardInstance.PublicIp}:1880/ui'
  AdminURL:
    Value: !Sub 'http://${DashboardInstance.PublicIp}:1880/admin'
  PublicIP:
    Value: !GetAtt DashboardInstance.PublicIp